from __future__ import annotations

import json
import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parent


class PackagingTests(unittest.TestCase):
    def test_dependencies_are_fully_pinned(self) -> None:
        lock = json.loads((ROOT / "dependencies.lock.json").read_text(encoding="utf-8"))
        for name in ("hidmaestro", "pythonEmbeddable", "dotnetSdk", "innoSetup"):
            dependency = lock[name]
            self.assertRegex(dependency["version"], r"^\d+\.\d+")
            self.assertTrue(dependency["downloadUrl"].startswith("https://"))
            self.assertGreater(dependency["assetSize"], 0)
            self.assertRegex(dependency["sha256"], r"^[0-9a-f]{64}$")
            self.assertTrue(dependency["license"])
            self.assertRegex(dependency["verifiedAt"], r"^\d{4}-\d{2}-\d{2}$")

    def test_vendored_qr_generator_is_pinned_and_not_a_runtime_download(self) -> None:
        lock = json.loads((ROOT / "dependencies.lock.json").read_text(encoding="utf-8"))
        qr = lock["qrcodegen"]
        self.assertEqual(qr["version"], "1.8.0")
        self.assertEqual(qr["license"], "MIT")
        self.assertTrue(qr["sourceUrl"].startswith("https://raw.githubusercontent.com/nayuki/"))
        self.assertRegex(qr["sourceSha256"], r"^[0-9a-f]{64}$")
        self.assertTrue((ROOT / "vendor" / "qrcodegen.py").is_file())
        self.assertTrue((ROOT / "vendor" / "LICENSE-qrcodegen.txt").is_file())

    def test_installer_has_fixed_app_id_and_private_firewall(self) -> None:
        script = (ROOT / "installer" / "CelularGamepad.iss").read_text(encoding="utf-8")
        self.assertIn("8C41B45B-1E31-4B85-93F8-E829A1A2DC42", script)
        add_rule = next(line for line in script.splitlines() if "firewall add rule" in line)
        self.assertIn("profile=private", add_rule.lower())
        self.assertNotRegex(add_rule.lower(), r"profile=(public|domain|any)")
        self.assertIn("HIDMaestro pode ser utilizado por outros programas e será preservado", script)

    def test_shortcut_targets_exist(self) -> None:
        for name in ("launch_emulators.cmd", "launch_xinput.cmd", "test_controllers.cmd", "verify_installation.cmd"):
            self.assertTrue((ROOT / "installer" / "scripts" / name).is_file(), name)

    def test_default_uninstall_never_removes_hidmaestro(self) -> None:
        cleanup = (ROOT / "installer" / "scripts" / "uninstall_cleanup.ps1").read_text(encoding="utf-8-sig")
        self.assertNotIn("--cleanup", cleanup)
        self.assertNotIn("remove_hidmaestro.ps1", cleanup)

    def test_build_is_self_contained_and_uses_staging(self) -> None:
        script = (ROOT / "scripts" / "build_installer.ps1").read_text(encoding="utf-8")
        self.assertIn("--self-contained true", script)
        self.assertIn("python.exe", script)
        self.assertIn("audit_installer.ps1", script)
        self.assertIn("qr_connection.py", script)
        self.assertIn("Join-Path $Root 'vendor'", script)

    def test_qr_pairing_has_no_external_client_resources_or_persistent_pin(self) -> None:
        app = (ROOT / "static" / "app.js").read_text(encoding="utf-8")
        index = (ROOT / "static" / "index.html").read_text(encoding="utf-8")
        self.assertNotIn("localStorage", app)
        self.assertIn("history.replaceState", (ROOT / "static" / "pairing_params.js").read_text(encoding="utf-8"))
        self.assertNotIn("http://", index)
        self.assertNotIn("https://", index)

    def test_generated_content_is_ignored(self) -> None:
        ignore = (ROOT / ".gitignore").read_text(encoding="utf-8")
        for entry in ("dist-release/", "installer/downloads/", "installer/output/", "installer/staging/"):
            self.assertIn(entry, ignore)

    def test_staging_is_clean_when_present(self) -> None:
        staging = ROOT / "installer" / "staging" / "app"
        if not staging.exists():
            self.skipTest("staging is generated by build_installer.ps1")
        self.assertTrue((staging / "runtime" / "python.exe").is_file())
        pth_files = list((staging / "runtime").glob("python*._pth"))
        self.assertEqual(len(pth_files), 1)
        self.assertIn("..", pth_files[0].read_text(encoding="ascii").splitlines())
        self.assertTrue((staging / "bridge" / "PhoneGamepad.Bridge.exe").is_file())
        self.assertTrue((staging / "bridge" / "coreclr.dll").is_file())
        self.assertFalse((staging / "config.json").exists())
        # Staging pode ter sido gerado por uma beta anterior; o build atual
        # sempre copia vendor e é validado pelo script/teste acima.
        if (staging / "vendor").exists():
            self.assertTrue((staging / "vendor" / "qrcodegen.py").is_file())
        for path in staging.rglob("*"):
            self.assertNotIn(path.name, {".git", ".github", "__pycache__", "config.json"})


if __name__ == "__main__":
    unittest.main(verbosity=2)
